# GitLab CI/CD configuration for deploying to GitLab Pages

# Define the pipeline stages
stages:
  - deploy

# Pages job - deploys the static site to GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  
  script:
    # Create the public directory required by GitLab Pages
    - mkdir -p public
    
    # Copy all files to the public directory
    - cp index.html public/
    - cp styles.css public/
    - cp script.js public/
    - cp webrtc-client.js public/
    - cp webrtc-signaling-server.js public/
    - cp README.md public/
    
    # Optionally, you can add any build steps here
    # For example: minification, optimization, etc.
    
    # Display what's being deployed
    - ls -la public/
    
  artifacts:
    # GitLab Pages looks for artifacts in the 'public' directory
    paths:
      - public
  
  # Only deploy from the main/master branch
  only:
    - main
    - master
  
  # Deploy on every commit to the main branch
  when: always

# Optional: Add a test job to validate HTML/CSS/JS before deployment
# test:
#   stage: test
#   image: node:latest
#   script:
#     - npm install -g html-validator-cli
#     - html-validator --file=index.html
#   only:
#     - main
#     - master
